# Generated by Django 3.2.8 on 2021-11-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
